//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CvManagementSystem.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LocalizationMarker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationMarker() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CvManagementSystem.Resources.LocalizationMarker", typeof(LocalizationMarker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have permission to view this page..
        /// </summary>
        public static string AccessDeniedMessage {
            get {
                return ResourceManager.GetString("AccessDeniedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDeniedTitle {
            get {
                return ResourceManager.GetString("AccessDeniedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add attribute.
        /// </summary>
        public static string AddAttributeBtn {
            get {
                return ResourceManager.GetString("AddAttributeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string AddButton {
            get {
                return ResourceManager.GetString("AddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add options that candidate will see.
        /// </summary>
        public static string AddOptionPrompt {
            get {
                return ResourceManager.GetString("AddOptionPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Add Project.
        /// </summary>
        public static string AddProjectBtn {
            get {
                return ResourceManager.GetString("AddProjectBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add project →.
        /// </summary>
        public static string AddProjectLink {
            get {
                return ResourceManager.GetString("AddProjectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tag.
        /// </summary>
        public static string AddTagBtn {
            get {
                return ResourceManager.GetString("AddTagBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., Python, Backend, Remote....
        /// </summary>
        public static string AddTagPlaceholder {
            get {
                return ResourceManager.GetString("AddTagPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All positions.
        /// </summary>
        public static string AllPositions {
            get {
                return ResourceManager.GetString("AllPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Positions →.
        /// </summary>
        public static string AllPositionsBtn {
            get {
                return ResourceManager.GetString("AllPositionsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already have an account? Login.
        /// </summary>
        public static string AlreadyHaveAccountPrompt {
            get {
                return ResourceManager.GetString("AlreadyHaveAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This attribute has already been added!.
        /// </summary>
        public static string AttrAlreadyAddedAlert {
            get {
                return ResourceManager.GetString("AttrAlreadyAddedAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        public static string AttributeColumn {
            get {
                return ResourceManager.GetString("AttributeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute: {0}.
        /// </summary>
        public static string AttributeDetails {
            get {
                return ResourceManager.GetString("AttributeDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Library.
        /// </summary>
        public static string AttributeLibrary {
            get {
                return ResourceManager.GetString("AttributeLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. GPA, English Level.
        /// </summary>
        public static string AttributeNamePlaceholder {
            get {
                return ResourceManager.GetString("AttributeNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string Attributes {
            get {
                return ResourceManager.GetString("Attributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string AttributesCountColumn {
            get {
                return ResourceManager.GetString("AttributesCountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes.
        /// </summary>
        public static string AttributesHeader {
            get {
                return ResourceManager.GetString("AttributesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes in library.
        /// </summary>
        public static string AttributesInLibrary {
            get {
                return ResourceManager.GetString("AttributesInLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No.
        /// </summary>
        public static string AttributeType_Boolean {
            get {
                return ResourceManager.GetString("AttributeType_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string AttributeType_Date {
            get {
                return ResourceManager.GetString("AttributeType_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown List.
        /// </summary>
        public static string AttributeType_Dropdown {
            get {
                return ResourceManager.GetString("AttributeType_Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string AttributeType_Image {
            get {
                return ResourceManager.GetString("AttributeType_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string AttributeType_Numeric {
            get {
                return ResourceManager.GetString("AttributeType_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string AttributeType_Period {
            get {
                return ResourceManager.GetString("AttributeType_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String.
        /// </summary>
        public static string AttributeType_String {
            get {
                return ResourceManager.GetString("AttributeType_String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text (Markdown).
        /// </summary>
        public static string AttributeType_Text {
            get {
                return ResourceManager.GetString("AttributeType_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute Type.
        /// </summary>
        public static string AttributeTypeLabel {
            get {
                return ResourceManager.GetString("AttributeTypeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available attributes from the library:.
        /// </summary>
        public static string AvailableAttributesHeader {
            get {
                return ResourceManager.GetString("AvailableAttributesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to available positions.
        /// </summary>
        public static string AvailablePositionsLink {
            get {
                return ResourceManager.GetString("AvailablePositionsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Positions.
        /// </summary>
        public static string AvailablePositionsTitle {
            get {
                return ResourceManager.GetString("AvailablePositionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackButton {
            get {
                return ResourceManager.GetString("BackButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Home.
        /// </summary>
        public static string BackToHome {
            get {
                return ResourceManager.GetString("BackToHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ← Back to position.
        /// </summary>
        public static string BackToPositionBtn {
            get {
                return ResourceManager.GetString("BackToPositionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes / No.
        /// </summary>
        public static string BooleanSwitchLabel {
            get {
                return ResourceManager.GetString("BooleanSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse positions.
        /// </summary>
        public static string BrowsePositions {
            get {
                return ResourceManager.GetString("BrowsePositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelBtn {
            get {
                return ResourceManager.GetString("CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate.
        /// </summary>
        public static string CandidateColumn {
            get {
                return ResourceManager.GetString("CandidateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates.
        /// </summary>
        public static string Candidates {
            get {
                return ResourceManager.GetString("Candidates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates&apos; CVs — {0}.
        /// </summary>
        public static string CandidatesCvsTitle {
            get {
                return ResourceManager.GetString("CandidatesCvsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate.
        /// </summary>
        public static string CandidateSection {
            get {
                return ResourceManager.GetString("CandidateSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidates.
        /// </summary>
        public static string CandidatesStat {
            get {
                return ResourceManager.GetString("CandidatesStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPasswordLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Attribute.
        /// </summary>
        public static string CreateAttribute {
            get {
                return ResourceManager.GetString("CreateAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string CreateButton {
            get {
                return ResourceManager.GetString("CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateCV.
        /// </summary>
        public static string CreateCvButton {
            get {
                return ResourceManager.GetString("CreateCvButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CV for position.
        /// </summary>
        public static string CreateCvForPosition {
            get {
                return ResourceManager.GetString("CreateCvForPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create CV.
        /// </summary>
        public static string CreateCvTitle {
            get {
                return ResourceManager.GetString("CreateCvTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string CreatedAtHeader {
            get {
                return ResourceManager.GetString("CreatedAtHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created at.
        /// </summary>
        public static string CreatedAtLabel {
            get {
                return ResourceManager.GetString("CreatedAtLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedByColumnLabel {
            get {
                return ResourceManager.GetString("CreatedByColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by.
        /// </summary>
        public static string CreatedByLabel {
            get {
                return ResourceManager.GetString("CreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Create New CV.
        /// </summary>
        public static string CreateNewCvBtn {
            get {
                return ResourceManager.GetString("CreateNewCvBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Position.
        /// </summary>
        public static string CreatePositionBtn {
            get {
                return ResourceManager.GetString("CreatePositionBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Position.
        /// </summary>
        public static string CreatePositionTitle {
            get {
                return ResourceManager.GetString("CreatePositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Project.
        /// </summary>
        public static string CreateProjectHeader {
            get {
                return ResourceManager.GetString("CreateProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Project.
        /// </summary>
        public static string CreateProjectTitle {
            get {
                return ResourceManager.GetString("CreateProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDateColumnLabel {
            get {
                return ResourceManager.GetString("CreationDateColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV will be automatically generated from your profile. Contains &lt;strong&gt;{0}&lt;/strong&gt; attributes..
        /// </summary>
        public static string CvAutoGenerationWarning {
            get {
                return ResourceManager.GetString("CvAutoGenerationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Created.
        /// </summary>
        public static string CvCreatedBadge {
            get {
                return ResourceManager.GetString("CvCreatedBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVs Created.
        /// </summary>
        public static string CvCreatedCountLabel {
            get {
                return ResourceManager.GetString("CvCreatedCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Created.
        /// </summary>
        public static string CvCreatedRow {
            get {
                return ResourceManager.GetString("CvCreatedRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Creation Date.
        /// </summary>
        public static string CvCreationDateColumn {
            get {
                return ResourceManager.GetString("CvCreationDateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVs.
        /// </summary>
        public static string CvsCountColumn {
            get {
                return ResourceManager.GetString("CvsCountColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVs created total.
        /// </summary>
        public static string CVsCreatedTotal {
            get {
                return ResourceManager.GetString("CVsCreatedTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVs for position: {0}.
        /// </summary>
        public static string CvsForPositionHeader {
            get {
                return ResourceManager.GetString("CvsForPositionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Status.
        /// </summary>
        public static string CvStatusHeader {
            get {
                return ResourceManager.GetString("CvStatusHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateColumn {
            get {
                return ResourceManager.GetString("DateColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteBtn {
            get {
                return ResourceManager.GetString("DeleteBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected attributes ({0} pcs.)?.
        /// </summary>
        public static string DeleteConfirmBulk {
            get {
                return ResourceManager.GetString("DeleteConfirmBulk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected positions ({0} pcs.)?.
        /// </summary>
        public static string DeleteConfirmBulkPositions {
            get {
                return ResourceManager.GetString("DeleteConfirmBulkPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete attribute?.
        /// </summary>
        public static string DeleteConfirmSingle {
            get {
                return ResourceManager.GetString("DeleteConfirmSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete CV.
        /// </summary>
        public static string DeleteCvButtonText {
            get {
                return ResourceManager.GetString("DeleteCvButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this CV?.
        /// </summary>
        public static string DeleteCvConfirm {
            get {
                return ResourceManager.GetString("DeleteCvConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this position?.
        /// </summary>
        public static string DeletePositionConfirm {
            get {
                return ResourceManager.GetString("DeletePositionConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        public static string DeleteSelected {
            get {
                return ResourceManager.GetString("DeleteSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Selected.
        /// </summary>
        public static string DeleteSelectedBtn {
            get {
                return ResourceManager.GetString("DeleteSelectedBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the selected positions ({0} items)?.
        /// </summary>
        public static string DeleteSelectedConfirm {
            get {
                return ResourceManager.GetString("DeleteSelectedConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionColumn {
            get {
                return ResourceManager.GetString("DescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionColumnLabel {
            get {
                return ResourceManager.GetString("DescriptionColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string DescriptionHeader {
            get {
                return ResourceManager.GetString("DescriptionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (optional).
        /// </summary>
        public static string DescriptionOptional {
            get {
                return ResourceManager.GetString("DescriptionOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (optional).
        /// </summary>
        public static string DescriptionOptionalLabel {
            get {
                return ResourceManager.GetString("DescriptionOptionalLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by.
        /// </summary>
        public static string DevelopedBy {
            get {
                return ResourceManager.GetString("DevelopedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is hidden from candidates.
        /// </summary>
        public static string DraftDescription {
            get {
                return ResourceManager.GetString("DraftDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string DraftState {
            get {
                return ResourceManager.GetString("DraftState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dropdown Options.
        /// </summary>
        public static string DropdownOptions {
            get {
                return ResourceManager.GetString("DropdownOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string DropdownSelectPlaceholder {
            get {
                return ResourceManager.GetString("DropdownSelectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate.
        /// </summary>
        public static string DuplicateBtn {
            get {
                return ResourceManager.GetString("DuplicateBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Attribute.
        /// </summary>
        public static string EditAttribute {
            get {
                return ResourceManager.GetString("EditAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditBtn {
            get {
                return ResourceManager.GetString("EditBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Position.
        /// </summary>
        public static string EditPositionTitle {
            get {
                return ResourceManager.GetString("EditPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string EditProjectHeader {
            get {
                return ResourceManager.GetString("EditProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Project.
        /// </summary>
        public static string EditProjectTitle {
            get {
                return ResourceManager.GetString("EditProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailFieldLabel {
            get {
                return ResourceManager.GetString("EmailFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EmailRow {
            get {
                return ResourceManager.GetString("EmailRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string EmptyValue {
            get {
                return ResourceManager.GetString("EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (leave blank if ongoing).
        /// </summary>
        public static string EndDateHint {
            get {
                return ResourceManager.GetString("EndDateHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDateLabel {
            get {
                return ResourceManager.GetString("EndDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter option....
        /// </summary>
        public static string EnterOptionPlaceholder {
            get {
                return ResourceManager.GetString("EnterOptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (filtered by position tags).
        /// </summary>
        public static string FilteredByTags {
            get {
                return ResourceManager.GetString("FilteredByTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullNameLabel {
            get {
                return ResourceManager.GetString("FullNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to John Doe.
        /// </summary>
        public static string FullNamePlaceholder {
            get {
                return ResourceManager.GetString("FullNamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Information.
        /// </summary>
        public static string GeneralInfoTitle {
            get {
                return ResourceManager.GetString("GeneralInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CV Management — Home.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload your image to Cloudinary and paste the link here.
        /// </summary>
        public static string ImageCloudinaryHint {
            get {
                return ResourceManager.GetString("ImageCloudinaryHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image URL (Cloudinary)....
        /// </summary>
        public static string ImagePlaceholderUrl {
            get {
                return ResourceManager.GetString("ImagePlaceholderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter number....
        /// </summary>
        public static string InputPlaceholderNumber {
            get {
                return ResourceManager.GetString("InputPlaceholderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text....
        /// </summary>
        public static string InputPlaceholderText {
            get {
                return ResourceManager.GetString("InputPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error adding attribute.
        /// </summary>
        public static string JsAddAttrError {
            get {
                return ResourceManager.GetString("JsAddAttrError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are unsaved changes....
        /// </summary>
        public static string JsChangesDetected {
            get {
                return ResourceManager.GetString("JsChangesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to )?.
        /// </summary>
        public static string JsConfirmDeleteEnd {
            get {
                return ResourceManager.GetString("JsConfirmDeleteEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  pcs.
        /// </summary>
        public static string JsConfirmDeletePcs {
            get {
                return ResourceManager.GetString("JsConfirmDeletePcs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected projects (.
        /// </summary>
        public static string JsConfirmDeleteStart {
            get {
                return ResourceManager.GetString("JsConfirmDeleteStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string JsError {
            get {
                return ResourceManager.GetString("JsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 10 tags allowed.
        /// </summary>
        public static string JsMaxTagsError {
            get {
                return ResourceManager.GetString("JsMaxTagsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection error.
        /// </summary>
        public static string JsNetworkError {
            get {
                return ResourceManager.GetString("JsNetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove attribute &quot;{0}&quot; from profile? The value will be deleted..
        /// </summary>
        public static string JsRemoveConfirm {
            get {
                return ResourceManager.GetString("JsRemoveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error removing attribute.
        /// </summary>
        public static string JsRemoveError {
            get {
                return ResourceManager.GetString("JsRemoveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        public static string JsSaved {
            get {
                return ResourceManager.GetString("JsSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving....
        /// </summary>
        public static string JsSaving {
            get {
                return ResourceManager.GetString("JsSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: .
        /// </summary>
        public static string JsSelectedPrefix {
            get {
                return ResourceManager.GetString("JsSelectedPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tag has already been added!.
        /// </summary>
        public static string JsTagDuplicateError {
            get {
                return ResourceManager.GetString("JsTagDuplicateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag cannot be longer than 50 characters.
        /// </summary>
        public static string JsTagLengthError {
            get {
                return ResourceManager.GetString("JsTagLengthError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library Attributes.
        /// </summary>
        public static string LibraryAttributesStat {
            get {
                return ResourceManager.GetString("LibraryAttributesStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string LoginButton {
            get {
                return ResourceManager.GetString("LoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LoginTitle {
            get {
                return ResourceManager.GetString("LoginTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with GitHub.
        /// </summary>
        public static string LoginWithGitHub {
            get {
                return ResourceManager.GetString("LoginWithGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in with Google.
        /// </summary>
        public static string LoginWithGoogle {
            get {
                return ResourceManager.GetString("LoginWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Information.
        /// </summary>
        public static string MainInfoSectionTitle {
            get {
                return ResourceManager.GetString("MainInfoSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage projects.
        /// </summary>
        public static string ManageProjectsBtn {
            get {
                return ResourceManager.GetString("ManageProjectsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Attributes.
        /// </summary>
        public static string MyAttributesSectionTitle {
            get {
                return ResourceManager.GetString("MyAttributesSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My CVs.
        /// </summary>
        public static string MyCVs {
            get {
                return ResourceManager.GetString("MyCVs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My CVs.
        /// </summary>
        public static string MyCvsTitle {
            get {
                return ResourceManager.GetString("MyCvsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string MyProjects {
            get {
                return ResourceManager.GetString("MyProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string MyProjectsHeader {
            get {
                return ResourceManager.GetString("MyProjectsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects are used during CV generation.
        /// </summary>
        public static string MyProjectsSectionHint {
            get {
                return ResourceManager.GetString("MyProjectsSectionHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string MyProjectsSectionTitle {
            get {
                return ResourceManager.GetString("MyProjectsSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Projects.
        /// </summary>
        public static string MyProjectsTitle {
            get {
                return ResourceManager.GetString("MyProjectsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameFieldLabel {
            get {
                return ResourceManager.GetString("NameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameLabel {
            get {
                return ResourceManager.GetString("NameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameRow {
            get {
                return ResourceManager.GetString("NameRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New CVs in 24h.
        /// </summary>
        public static string NewCVs24h {
            get {
                return ResourceManager.GetString("NewCVs24h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New CVs (24 Hours).
        /// </summary>
        public static string NewCvs24hStat {
            get {
                return ResourceManager.GetString("NewCvs24hStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New option....
        /// </summary>
        public static string NewOptionPlaceholder {
            get {
                return ResourceManager.GetString("NewOptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Python, Django, PostgreSQL....
        /// </summary>
        public static string NewTagPlaceholder {
            get {
                return ResourceManager.GetString("NewTagPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account? Register.
        /// </summary>
        public static string NoAccountPrompt {
            get {
                return ResourceManager.GetString("NoAccountPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attributes.
        /// </summary>
        public static string NoAttributes {
            get {
                return ResourceManager.GetString("NoAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attributes added.
        /// </summary>
        public static string NoAttributesAlert {
            get {
                return ResourceManager.GetString("NoAttributesAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t added any attributes yet. Click &quot;+ Add attribute&quot; to get started..
        /// </summary>
        public static string NoAttributesAlertText {
            get {
                return ResourceManager.GetString("NoAttributesAlertText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No attributes yet. Create the first one!.
        /// </summary>
        public static string NoAttributesYet {
            get {
                return ResourceManager.GetString("NoAttributesYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No CV.
        /// </summary>
        public static string NoCvBadge {
            get {
                return ResourceManager.GetString("NoCvBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No candidate has created a CV for this position yet..
        /// </summary>
        public static string NoCvsForPositionAlert {
            get {
                return ResourceManager.GetString("NoCvsForPositionAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to the available positions section and create a CV for the position you are interested in..
        /// </summary>
        public static string NoCvsYetMessage {
            get {
                return ResourceManager.GetString("NoCvsYetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have any CVs yet.
        /// </summary>
        public static string NoCvsYetTitle {
            get {
                return ResourceManager.GetString("NoCvsYetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No matching projects found..
        /// </summary>
        public static string NoMatchingProjects {
            get {
                return ResourceManager.GetString("NoMatchingProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No positions available yet..
        /// </summary>
        public static string NoPositionsAlert {
            get {
                return ResourceManager.GetString("NoPositionsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No positions available at the moment. Check back later!.
        /// </summary>
        public static string NoPositionsAvailable {
            get {
                return ResourceManager.GetString("NoPositionsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No positions available yet.
        /// </summary>
        public static string NoPositionsYet {
            get {
                return ResourceManager.GetString("NoPositionsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No projects yet. Add your first one!.
        /// </summary>
        public static string NoProjectsAlert {
            get {
                return ResourceManager.GetString("NoProjectsAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rights reserved whatsoever 🙂.
        /// </summary>
        public static string NoRightsReserved {
            get {
                return ResourceManager.GetString("NoRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags available yet.
        /// </summary>
        public static string NoTagsYet {
            get {
                return ResourceManager.GetString("NoTagsYet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not filled.
        /// </summary>
        public static string NotFilled {
            get {
                return ResourceManager.GetString("NotFilled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not filled — fill in profile →.
        /// </summary>
        public static string NotFilledFillInProfile {
            get {
                return ResourceManager.GetString("NotFilledFillInProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open positions.
        /// </summary>
        public static string OpenPositions {
            get {
                return ResourceManager.GetString("OpenPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Positions.
        /// </summary>
        public static string OpenPositionsStat {
            get {
                return ResourceManager.GetString("OpenPositionsStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options Count.
        /// </summary>
        public static string OptionsCountLabel {
            get {
                return ResourceManager.GetString("OptionsCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Or log in with.
        /// </summary>
        public static string OrLoginWith {
            get {
                return ResourceManager.GetString("OrLoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordLabel {
            get {
                return ResourceManager.GetString("PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        public static string PeriodColumn {
            get {
                return ResourceManager.GetString("PeriodColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular tags.
        /// </summary>
        public static string PopularTags {
            get {
                return ResourceManager.GetString("PopularTags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Tags.
        /// </summary>
        public static string PopularTagsHeader {
            get {
                return ResourceManager.GetString("PopularTagsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose which attributes the candidate needs to fill out for this position.
        /// </summary>
        public static string PositionAttributesHelpText {
            get {
                return ResourceManager.GetString("PositionAttributesHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Attributes.
        /// </summary>
        public static string PositionAttributesLabel {
            get {
                return ResourceManager.GetString("PositionAttributesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PositionHeader {
            get {
                return ResourceManager.GetString("PositionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string Positions {
            get {
                return ResourceManager.GetString("Positions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Positions.
        /// </summary>
        public static string PositionsIndexTitle {
            get {
                return ResourceManager.GetString("PositionsIndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Title.
        /// </summary>
        public static string PositionTitleLabel {
            get {
                return ResourceManager.GetString("PositionTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., Junior Backend Developer.
        /// </summary>
        public static string PositionTitlePlaceholder {
            get {
                return ResourceManager.GetString("PositionTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position: {0}.
        /// </summary>
        public static string PositionTitlePrefix {
            get {
                return ResourceManager.GetString("PositionTitlePrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to present.
        /// </summary>
        public static string PresentTime {
            get {
                return ResourceManager.GetString("PresentTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to present.
        /// </summary>
        public static string PresentTimeValue {
            get {
                return ResourceManager.GetString("PresentTimeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, we collect your name, email, GPA, English level, marital status, and literally everything else you put in your profile. We promise not to sell it. Probably..
        /// </summary>
        public static string PrivacyCollectText {
            get {
                return ResourceManager.GetString("PrivacyCollectText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We collect your data.
        /// </summary>
        public static string PrivacyCollectTitle {
            get {
                return ResourceManager.GetString("PrivacyCollectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you have any concerns about your privacy, please write them on a piece of paper and throw it away. Or email us. We might respond..
        /// </summary>
        public static string PrivacyContactText {
            get {
                return ResourceManager.GetString("PrivacyContactText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string PrivacyContactTitle {
            get {
                return ResourceManager.GetString("PrivacyContactTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We use cookies. Not the chocolate chip kind, unfortunately. Just the boring authentication kind that keeps you logged in..
        /// </summary>
        public static string PrivacyCookiesText {
            get {
                return ResourceManager.GetString("PrivacyCookiesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string PrivacyCookiesTitle {
            get {
                return ResourceManager.GetString("PrivacyCookiesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last updated: never. This policy is eternal and immutable, like the laws of physics, but less reliable. © {0} Abay Tolegen. No rights reserved whatsoever..
        /// </summary>
        public static string PrivacyFooterText {
            get {
                return ResourceManager.GetString("PrivacyFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicyTitle {
            get {
                return ResourceManager.GetString("PrivacyPolicyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the right to remain silent. Anything you type into your profile can and will be used against you in a CV review..
        /// </summary>
        public static string PrivacyRightsText {
            get {
                return ResourceManager.GetString("PrivacyRightsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your rights.
        /// </summary>
        public static string PrivacyRightsTitle {
            get {
                return ResourceManager.GetString("PrivacyRightsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is hashed with a secure algorithm. We have no idea what your password is. Neither does anyone else. Including you, probably..
        /// </summary>
        public static string PrivacySecurityText {
            get {
                return ResourceManager.GetString("PrivacySecurityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string PrivacySecurityTitle {
            get {
                return ResourceManager.GetString("PrivacySecurityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string ProfileHeader {
            get {
                return ResourceManager.GetString("ProfileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string ProfileTitle {
            get {
                return ResourceManager.GetString("ProfileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description (optional).
        /// </summary>
        public static string ProjectDescriptionLabel {
            get {
                return ResourceManager.GetString("ProjectDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Describe what you did, what technologies you used....
        /// </summary>
        public static string ProjectDescriptionPlaceholder {
            get {
                return ResourceManager.GetString("ProjectDescriptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string ProjectsHeader {
            get {
                return ResourceManager.GetString("ProjectsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string ProjectsSection {
            get {
                return ResourceManager.GetString("ProjectsSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Title.
        /// </summary>
        public static string ProjectTitleLabel {
            get {
                return ResourceManager.GetString("ProjectTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g., Online store using Django.
        /// </summary>
        public static string ProjectTitlePlaceholder {
            get {
                return ResourceManager.GetString("ProjectTitlePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publication Status.
        /// </summary>
        public static string PublicationStatusLabel {
            get {
                return ResourceManager.GetString("PublicationStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position is visible to candidates.
        /// </summary>
        public static string PublishedDescription {
            get {
                return ResourceManager.GetString("PublishedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Published.
        /// </summary>
        public static string PublishedState {
            get {
                return ResourceManager.GetString("PublishedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start?.
        /// </summary>
        public static string ReadyToStart {
            get {
                return ResourceManager.GetString("ReadyToStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start?.
        /// </summary>
        public static string ReadyToStartHeader {
            get {
                return ResourceManager.GetString("ReadyToStartHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a candidate and create CVs for the positions you are interested in.
        /// </summary>
        public static string ReadyToStartText {
            get {
                return ResourceManager.GetString("ReadyToStartText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent positions.
        /// </summary>
        public static string RecentPositions {
            get {
                return ResourceManager.GetString("RecentPositions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Positions.
        /// </summary>
        public static string RecentPositionsHeader {
            get {
                return ResourceManager.GetString("RecentPositionsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiters.
        /// </summary>
        public static string Recruiters {
            get {
                return ResourceManager.GetString("Recruiters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiters.
        /// </summary>
        public static string RecruitersStat {
            get {
                return ResourceManager.GetString("RecruitersStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I am registering as.
        /// </summary>
        public static string RegisterAsLabel {
            get {
                return ResourceManager.GetString("RegisterAsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButton {
            get {
                return ResourceManager.GetString("RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register as a candidate and create CVs for positions you&apos;re interested in.
        /// </summary>
        public static string RegisterPrompt {
            get {
                return ResourceManager.GetString("RegisterPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterTitle {
            get {
                return ResourceManager.GetString("RegisterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveAttributeBtn {
            get {
                return ResourceManager.GetString("RemoveAttributeBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveBtn {
            get {
                return ResourceManager.GetString("RemoveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RequiredAttributeBadge {
            get {
                return ResourceManager.GetString("RequiredAttributeBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RequiredBadge {
            get {
                return ResourceManager.GetString("RequiredBadge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveBtn {
            get {
                return ResourceManager.GetString("SaveBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a search query.
        /// </summary>
        public static string SearchEnterQuery {
            get {
                return ResourceManager.GetString("SearchEnterQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing found for.
        /// </summary>
        public static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string SearchPlaceholder {
            get {
                return ResourceManager.GetString("SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for.
        /// </summary>
        public static string SearchResultsFor {
            get {
                return ResourceManager.GetString("SearchResultsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Results.
        /// </summary>
        public static string SearchResultsTitle {
            get {
                return ResourceManager.GetString("SearchResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: {0}.
        /// </summary>
        public static string SelectedCount {
            get {
                return ResourceManager.GetString("SelectedCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected: {0}.
        /// </summary>
        public static string SelectedCountText {
            get {
                return ResourceManager.GetString("SelectedCountText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDateLabel {
            get {
                return ResourceManager.GetString("StartDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusColumn {
            get {
                return ResourceManager.GetString("StatusColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusColumnLabel {
            get {
                return ResourceManager.GetString("StatusColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string StatusEmpty {
            get {
                return ResourceManager.GetString("StatusEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not filled!.
        /// </summary>
        public static string StatusNotFilledWarning {
            get {
                return ResourceManager.GetString("StatusNotFilledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsColumn {
            get {
                return ResourceManager.GetString("TagsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsHeader {
            get {
                return ResourceManager.GetString("TagsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags are used to filter projects in the CV.
        /// </summary>
        public static string TagsHint {
            get {
                return ResourceManager.GetString("TagsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string TagsLabel {
            get {
                return ResourceManager.GetString("TagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology Tags.
        /// </summary>
        public static string TechnologyTagsLabel {
            get {
                return ResourceManager.GetString("TechnologyTagsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleColumn {
            get {
                return ResourceManager.GetString("TitleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string TitleColumnLabel {
            get {
                return ResourceManager.GetString("TitleColumnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total CVs Created.
        /// </summary>
        public static string TotalCvsStat {
            get {
                return ResourceManager.GetString("TotalCvsStat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute type cannot be changed after creation.
        /// </summary>
        public static string TypeChangeWarning {
            get {
                return ResourceManager.GetString("TypeChangeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        public static string UserRole_Administrator {
            get {
                return ResourceManager.GetString("UserRole_Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate.
        /// </summary>
        public static string UserRole_Candidate {
            get {
                return ResourceManager.GetString("UserRole_Candidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recruiter.
        /// </summary>
        public static string UserRole_Recruiter {
            get {
                return ResourceManager.GetString("UserRole_Recruiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string ValueColumn {
            get {
                return ResourceManager.GetString("ValueColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View CVs ({0}).
        /// </summary>
        public static string ViewCvsCountBtn {
            get {
                return ResourceManager.GetString("ViewCvsCountBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Positions.
        /// </summary>
        public static string ViewPositionsBtn {
            get {
                return ResourceManager.GetString("ViewPositionsBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
